"""
MarkdownPublicationReadmeWriter — README в корне публикации (T035 Phase 2.4).

Layout (FR §3):

    <out_dir>/README.md
    <out_dir>/schematic/...      (если bundle.schematic не None)
    <out_dir>/sim-report/...     (если bundle.sim_report не None)

README ссылается на файлы относительными путями от `out_dir`.

i18n: `_README_LABELS[PublicationLang]` — ~15 строк key/value для
ru/en (A-7).
"""

from __future__ import annotations

import asyncio
import os
from typing import TYPE_CHECKING

from domain.publication import PublicationLang
from ports.outbound.publication_readme_writer import PublicationReadmeWriteError

if TYPE_CHECKING:
    from pathlib import Path

    from domain.publication import (
        PublicationBundle,
        SchematicPublicationArtifacts,
        SheetArtifactSet,
        SimReportArtifacts,
    )


_README_LABELS: dict[PublicationLang, dict[str, str]] = {
    PublicationLang.RU: {
        'title': 'Публикация',
        'metadata_h2': 'Метаданные',
        'project': 'Проект',
        'date': 'Дата',
        'efactory_version': 'Версия efactory',
        'lang': 'Язык',
        'schematic_h2': 'Схема (publication-grade)',
        'color_h3': 'Цветная версия',
        'bw_h3': 'Чёрно-белая версия',
        'per_sheet_h4': 'По листам (per-sheet)',
        'combined_h4': 'Объединённый PDF',
        'sheet_col': 'Лист',
        'svg_col': 'SVG (vector)',
        'pdf_col': 'PDF (vector)',
        'png_col': 'PNG (300 DPI)',
        'sim_report_h2': 'Отчёт о симуляции',
        'main_doc': 'Главный документ',
        'plots': 'Графики',
        'plot_count_one': 'график',
        'plot_count_many': 'графиков',
        'tables': 'Таблицы',
        'no_tables': 'отсутствуют',
        'source_sim_label': 'Источник симуляции',
        'fresh_run': 'свежий прогон (--rerun)',
        'dpi_note': '300 DPI',
        'note_h2': 'Примечание',
        'note_body': (
            'Сгенерировано `/export-schematic-publication` / '
            '`/export-sim-report` (efactory T035). PNG @ 300 DPI '
            'пригодны для печатной публикации; SVG/PDF — векторные.'
        ),
    },
    PublicationLang.EN: {
        'title': 'Publication',
        'metadata_h2': 'Metadata',
        'project': 'Project',
        'date': 'Date',
        'efactory_version': 'efactory version',
        'lang': 'Language',
        'schematic_h2': 'Schematic (publication-grade)',
        'color_h3': 'Color version',
        'bw_h3': 'Black-and-white version',
        'per_sheet_h4': 'Per-sheet',
        'combined_h4': 'Combined PDF',
        'sheet_col': 'Sheet',
        'svg_col': 'SVG (vector)',
        'pdf_col': 'PDF (vector)',
        'png_col': 'PNG (300 DPI)',
        'sim_report_h2': 'Simulation report',
        'main_doc': 'Main document',
        'plots': 'Plots',
        'plot_count_one': 'plot',
        'plot_count_many': 'plots',
        'tables': 'Tables',
        'no_tables': 'none',
        'source_sim_label': 'Simulation source',
        'fresh_run': 'fresh run (--rerun)',
        'dpi_note': '300 DPI',
        'note_h2': 'Note',
        'note_body': (
            'Generated by `/export-schematic-publication` / '
            '`/export-sim-report` (efactory T035). PNGs @ 300 DPI are '
            'print-publication grade; SVG/PDF are vector.'
        ),
    },
}


class MarkdownPublicationReadmeWriter:
    """PublicationReadmeWriter на Markdown (T035 Phase 2.4)."""

    async def write(
        self,
        bundle: PublicationBundle,
        *,
        out_dir: Path,
    ) -> Path:
        return await asyncio.to_thread(self._write_sync, bundle, out_dir)

    def _write_sync(self, bundle: PublicationBundle, out_dir: Path) -> Path:
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            msg = f'MarkdownPublicationReadmeWriter: cannot create {out_dir}: {exc}'
            raise PublicationReadmeWriteError(msg) from exc

        labels = _README_LABELS[bundle.lang]
        lines: list[str] = []

        lines.append(f'# {labels["title"]} — {bundle.project}')
        lines.append('')

        lines.extend(_render_metadata(bundle, labels))

        if bundle.schematic is not None:
            lines.extend(
                _render_schematic_section(bundle.schematic, out_dir, labels),
            )

        if bundle.sim_report is not None:
            lines.extend(
                _render_sim_report_section(bundle.sim_report, out_dir, labels),
            )

        lines.append(f'## {labels["note_h2"]}')
        lines.append('')
        lines.append(labels['note_body'])
        lines.append('')

        readme_path = out_dir / 'README.md'
        try:
            readme_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
        except OSError as exc:
            msg = f'MarkdownPublicationReadmeWriter: cannot write {readme_path}: {exc}'
            raise PublicationReadmeWriteError(msg) from exc

        return readme_path


def _render_metadata(
    bundle: PublicationBundle,
    labels: dict[str, str],
) -> list[str]:
    return [
        f'## {labels["metadata_h2"]}',
        '',
        f'- **{labels["project"]}:** {bundle.project}',
        f'- **{labels["date"]}:** {bundle.timestamp.isoformat()}',
        f'- **{labels["efactory_version"]}:** {bundle.efactory_version}',
        f'- **{labels["lang"]}:** {bundle.lang.value}',
        '',
    ]


def _render_schematic_section(
    schematic: SchematicPublicationArtifacts,
    out_dir: Path,
    labels: dict[str, str],
) -> list[str]:
    lines = [f'## {labels["schematic_h2"]}', '']

    lines.append(f'### {labels["color_h3"]}')
    lines.append('')
    lines.extend(
        _render_sheet_table(schematic.color_per_sheet, out_dir, labels),
    )
    if schematic.color_combined is not None:
        lines.extend(
            _render_combined_block(schematic.color_combined, out_dir, labels),
        )

    lines.append(f'### {labels["bw_h3"]}')
    lines.append('')
    lines.extend(
        _render_sheet_table(schematic.bw_per_sheet, out_dir, labels),
    )
    if schematic.bw_combined is not None:
        lines.extend(
            _render_combined_block(schematic.bw_combined, out_dir, labels),
        )

    return lines


def _render_sheet_table(
    sheets: tuple[SheetArtifactSet, ...],
    out_dir: Path,
    labels: dict[str, str],
) -> list[str]:
    lines = [f'#### {labels["per_sheet_h4"]}', '']
    lines.append(
        f'| {labels["sheet_col"]} | {labels["svg_col"]} | '
        f'{labels["pdf_col"]} | {labels["png_col"]} |',
    )
    lines.append('|---|---|---|---|')
    for s in sheets:
        svg_rel = _relpath(s.svg, out_dir)
        pdf_rel = _relpath(s.pdf, out_dir)
        png_rel = _relpath(s.png, out_dir)
        lines.append(
            f'| {s.sheet_name} | [{svg_rel}]({svg_rel}) | '
            f'[{pdf_rel}]({pdf_rel}) | [{png_rel}]({png_rel}) |',
        )
    lines.append('')
    return lines


def _render_combined_block(
    combined_path: Path,
    out_dir: Path,
    labels: dict[str, str],
) -> list[str]:
    rel = _relpath(combined_path, out_dir)
    return [
        f'#### {labels["combined_h4"]}',
        '',
        f'- [{rel}]({rel})',
        '',
    ]


def _render_sim_report_section(
    sim_report: SimReportArtifacts,
    out_dir: Path,
    labels: dict[str, str],
) -> list[str]:
    lines = [f'## {labels["sim_report_h2"]}', '']
    report_rel = _relpath(sim_report.report_md, out_dir)
    lines.append(f'- **{labels["main_doc"]}:** [{report_rel}]({report_rel})')

    n = len(sim_report.plots)
    plot_word = labels['plot_count_one'] if n == 1 else labels['plot_count_many']
    lines.append(
        f'- **{labels["plots"]}:** {n} {plot_word} ({labels["dpi_note"]}):',
    )
    for p in sim_report.plots:
        rel = _relpath(p, out_dir)
        lines.append(f'  - [{rel}]({rel})')

    if sim_report.tables:
        lines.append(f'- **{labels["tables"]}:**')
        for t in sim_report.tables:
            rel = _relpath(t, out_dir)
            lines.append(f'  - [{rel}]({rel})')
    else:
        lines.append(f'- **{labels["tables"]}:** {labels["no_tables"]}')

    source_display = (
        sim_report.source_simulation_ts.isoformat()
        if sim_report.source_simulation_ts is not None
        else labels['fresh_run']
    )
    lines.append(f'- **{labels["source_sim_label"]}:** {source_display}')
    lines.append('')
    return lines


def _relpath(path: Path, base: Path) -> str:
    """
    Best-effort relative path в POSIX-форме (для Markdown ссылок).

    `Path.relative_to(base)` валит ошибку если path не под base; в этом
    случае используем `os.path.relpath` (даёт `../...` либо абсолют для
    разных дисков на Windows).
    """
    try:
        return path.relative_to(base).as_posix()
    except ValueError:
        return os.path.relpath(path, base).replace(os.sep, '/')


__all__ = ['MarkdownPublicationReadmeWriter']
