"""
GetDP magnetostatic .pro templates (T113 Phase 2C + T129 Phase A).

Два варианта формулировки:

- **Linear** (`render_magnetostatic_pro`, back-compat default) —
  constant μ_r в iron region. Pilot Stage B+C baseline.
- **Nonlinear-Frohlich** (`render_magnetostatic_pro_nonlinear`,
  T129 Phase A) — tabulated ν(B) через GetDP `InterpolationLinear`
  + fixed-point Picard `IterativeLoop` (tol 1e-5, max 50,
  relaxation 0.7). BH-таблица генерируется
  `FrohlichBHCurve.from_pyom_material()` из (μ_initial, B_sat).

Linear template портирован из `scripts/pilot/getdp/magnetostatic.pro`
(pilot Stage B+C, commit 9c42042; 5 итераций debug на
BF_PerpendicularEdge + Vector[Jz] + split current direction).

4 параметра linear-варианта подставляются адаптером per-component:
- `mur_iron` — relative permeability iron (`Core` region).
- `n_primary` — число витков primary winding.
- `i_ref` — reference current (1.0 A штатно для self-inductance).
- `area_window` — площадь окна primary (m²) для J_density расчёта.

Nonlinear-вариант заменяет `mur_iron` на `bh_list_literal` —
GetDP `{B0, nu0, B1, nu1, ...}` literal от
`FrohlichBHCurve.as_getdp_list_literal()`.
"""

from __future__ import annotations

NL_MAX_ITER = 50
NL_TOL = 1.0e-5
NL_RELAXATION = 0.7

PRO_TEMPLATE = """\
// efactory adapters.outbound.fem_solver_getdp magnetostatic .pro
// Generated by pro_template.render() — НЕ ПРАВИТЬ ВРУЧНУЮ
//
// 2D-planar magnetostatic: vector potential A_z формулировка через
// BF_PerpendicularEdge. Lp = 2 W / I_ref² где W — energy_per_depth
// × core_depth (умножается на стороне adapter'а).
//
// PG mapping (см. geometry.emit_e_core_geo):
//   1=Core 2=Primary 3=Secondary 4=GapC 5=GapL 6=GapR 7=Air 8=Infinity

Group {{
  Core      = Region[1];
  Primary   = Region[2];
  Secondary = Region[3];
  GapC      = Region[4];
  GapL      = Region[5];
  GapR      = Region[6];
  Air       = Region[7];
  Infinity  = Region[8];

  Iron     = Region[{{Core}}];
  NonIron  = Region[{{Primary, Secondary, GapC, GapL, GapR, Air}}];
  Domain   = Region[{{Iron, NonIron}}];
}}

Function {{
  mu0      = 4*Pi*1e-7;
  mur_iron = {mur_iron};

  nu[Iron]     = 1.0 / (mu0 * mur_iron);
  nu[NonIron]  = 1.0 / mu0;

  // Coil topology (per pilot Stage B+C debug): split current direction
  // — +Jz в Primary window, -Jz в Secondary (reinterpreted как
  // return-leg). Без split одно-окно prescription = одиночный провод,
  // Lp завышена ~2.8×.
  N_primary    = {n_primary};
  I_ref        = {i_ref:g};
  area_window  = {area_window:g};
  J_density    = N_primary * I_ref / area_window;

  js[Primary]   = Vector[0, 0,  J_density];
  js[Secondary] = Vector[0, 0, -J_density];
}}

Constraint {{
  {{ Name MVP_2D;
    Case {{
      {{ Region Infinity; Value 0.; }}
    }}
  }}
}}

FunctionSpace {{
  {{ Name Hcurl_a_2D; Type Form1P;
    BasisFunction {{
      {{ Name sn; NameOfCoef an;
        Function BF_PerpendicularEdge;
        Support Domain; Entity NodesOf[All]; }}
    }}
    Constraint {{
      {{ NameOfCoef an; EntityType NodesOf; NameOfConstraint MVP_2D; }}
    }}
  }}
}}

Jacobian {{
  {{ Name Vol; Case {{ {{ Region All; Jacobian Vol; }} }} }}
}}

Integration {{
  {{ Name I1;
    Case {{
      {{ Type Gauss;
        Case {{
          {{ GeoElement Triangle;  NumberOfPoints  3; }}
          {{ GeoElement Triangle2; NumberOfPoints  6; }}
          {{ GeoElement Line;      NumberOfPoints  1; }}
          {{ GeoElement Line2;     NumberOfPoints  3; }}
        }}
      }}
    }}
  }}
}}

Formulation {{
  {{ Name Magnetostatics_2D; Type FemEquation;
    Quantity {{
      {{ Name a; Type Local; NameOfSpace Hcurl_a_2D; }}
    }}
    Equation {{
      Galerkin {{ [ nu[] * Dof{{d a}}, {{d a}} ];
                 In Domain; Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Primary;   Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Secondary; Jacobian Vol; Integration I1; }}
    }}
  }}
}}

Resolution {{
  {{ Name Mag2D;
    System {{
      {{ Name A; NameOfFormulation Magnetostatics_2D; }}
    }}
    Operation {{
      Generate[A]; Solve[A]; SaveSolution[A];
      PostOperation[Mag2D];
    }}
  }}
}}

PostProcessing {{
  {{ Name Mag2D; NameOfFormulation Magnetostatics_2D;
    Quantity {{
      {{ Name energy_per_depth;
        Value {{
          Integral {{ [ 0.5 * nu[] * {{d a}} * {{d a}} ];
                     In Domain; Jacobian Vol; Integration I1; }}
        }}
      }}
    }}
  }}
}}

PostOperation {{
  {{ Name Mag2D; NameOfPostProcessing Mag2D;
    Operation {{
      Print[ energy_per_depth[Domain], OnGlobal, Format Table,
             File "energy_per_depth.txt" ];
    }}
  }}
}}
"""


PRO_TEMPLATE_NONLINEAR = """\
// efactory adapters.outbound.fem_solver_getdp magnetostatic nonlinear .pro
// Generated by pro_template.render_nonlinear() — НЕ ПРАВИТЬ ВРУЧНУЮ
//
// 2D-planar magnetostatic с Frohlich-Kennelly BH-кривой (T129).
// ν(B) — InterpolationLinear по таблице {{B0, nu0, B1, nu1, ...}};
// fixed-point Picard через IterativeLoop[max, tol, relax].
// Geometry/coil topology идентичны linear-варианту.

Group {{
  Core      = Region[1];
  Primary   = Region[2];
  Secondary = Region[3];
  GapC      = Region[4];
  GapL      = Region[5];
  GapR      = Region[6];
  Air       = Region[7];
  Infinity  = Region[8];

  Iron     = Region[{{Core}}];
  NonIron  = Region[{{Primary, Secondary, GapC, GapL, GapR, Air}}];
  Domain   = Region[{{Iron, NonIron}}];
}}

Function {{
  mu0      = 4*Pi*1e-7;

  // Tabulated ν(B) from Frohlich-Kennelly (μ_initial, B_sat) → reluctivity
  // {{B0,nu0, B1,nu1, ...}}; первая точка (0, 1/(μ₀·μ_init)) задаёт
  // касательную в нуле, остальные — chord ν = H/B.
  //
  // GetDP discipline: nu[Region] объявляется как функция $1 (B norm), в
  // Galerkin/PostProcessing вызывается с явным аргументом — `{{d a}}` нельзя
  // использовать прямо в Function (discrete quantity available only в
  // Galerkin/PP context). См. femmt/electro_magnetic/ind_axi_python_*.pro.
  nu[Iron]    = InterpolationLinear[ Norm[$1] ]{{ List[{bh_list_literal}] }};
  nu[NonIron] = 1.0 / mu0;

  // Coil topology идентична linear: split current direction
  // +Jz в Primary, -Jz в Secondary (T113 pilot Stage B+C).
  N_primary    = {n_primary};
  I_ref        = {i_ref:g};
  area_window  = {area_window:g};
  J_density    = N_primary * I_ref / area_window;

  js[Primary]   = Vector[0, 0,  J_density];
  js[Secondary] = Vector[0, 0, -J_density];
}}

Constraint {{
  {{ Name MVP_2D;
    Case {{
      {{ Region Infinity; Value 0.; }}
    }}
  }}
}}

FunctionSpace {{
  {{ Name Hcurl_a_2D; Type Form1P;
    BasisFunction {{
      {{ Name sn; NameOfCoef an;
        Function BF_PerpendicularEdge;
        Support Domain; Entity NodesOf[All]; }}
    }}
    Constraint {{
      {{ NameOfCoef an; EntityType NodesOf; NameOfConstraint MVP_2D; }}
    }}
  }}
}}

Jacobian {{
  {{ Name Vol; Case {{ {{ Region All; Jacobian Vol; }} }} }}
}}

Integration {{
  {{ Name I1;
    Case {{
      {{ Type Gauss;
        Case {{
          {{ GeoElement Triangle;  NumberOfPoints  3; }}
          {{ GeoElement Triangle2; NumberOfPoints  6; }}
          {{ GeoElement Line;      NumberOfPoints  1; }}
          {{ GeoElement Line2;     NumberOfPoints  3; }}
        }}
      }}
    }}
  }}
}}

Formulation {{
  {{ Name Magnetostatics_2D; Type FemEquation;
    Quantity {{
      {{ Name a; Type Local; NameOfSpace Hcurl_a_2D; }}
    }}
    Equation {{
      // nu[Region][$1] — Iron tabulated, NonIron constant — вызывается с
      // current B = {{d a}} для Picard re-evaluation на каждой итерации.
      Galerkin {{ [ nu[{{d a}}] * Dof{{d a}}, {{d a}} ];
                 In Domain; Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Primary;   Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Secondary; Jacobian Vol; Integration I1; }}
    }}
  }}
}}

Resolution {{
  {{ Name Mag2D;
    System {{
      {{ Name A; NameOfFormulation Magnetostatics_2D; }}
    }}
    Operation {{
      // Picard fixed-point: на каждой итерации ν[Iron] re-evaluates
      // от текущего |{{d a}}|; релаксация {nl_relax:g} даёт устойчивость
      // в deep saturation (H_dc >> H_sat).
      IterativeLoop[ {nl_max_iter}, {nl_tol:g}, {nl_relax:g} ] {{
        Generate[A]; Solve[A];
      }}
      SaveSolution[A];
      PostOperation[Mag2D];
    }}
  }}
}}

PostProcessing {{
  {{ Name Mag2D; NameOfFormulation Magnetostatics_2D;
    Quantity {{
      {{ Name energy_per_depth;
        Value {{
          Integral {{ [ 0.5 * nu[{{d a}}] * {{d a}} * {{d a}} ];
                     In Domain; Jacobian Vol; Integration I1; }}
        }}
      }}
      // Flux linkage primary winding (per unit depth):
      //   Ψ_per_depth = (N_primary / area_window) · ∫_Primary A_z dA
      // CompZ[{{a}}] = A_z в 2D-planar с BF_PerpendicularEdge formulation.
      // Adapter умножит на core_depth для Wb.
      {{ Name flux_linkage_per_depth;
        Value {{
          Integral {{ [ (N_primary / area_window) * CompZ[{{a}}] ];
                     In Primary; Jacobian Vol; Integration I1; }}
        }}
      }}
    }}
  }}
}}

PostOperation {{
  {{ Name Mag2D; NameOfPostProcessing Mag2D;
    Operation {{
      Print[ energy_per_depth[Domain], OnGlobal, Format Table,
             File "energy_per_depth.txt" ];
      Print[ flux_linkage_per_depth[Primary], OnGlobal, Format Table,
             File "flux_linkage.txt" ];
    }}
  }}
}}
"""


def render_magnetostatic_pro(
    *,
    mur_iron: float,
    n_primary: int,
    i_ref: float,
    area_window: float,
) -> str:
    """Linear-μ_r magnetostatic .pro (back-compat default; pilot Stage B+C)."""
    return PRO_TEMPLATE.format(
        mur_iron=mur_iron,
        n_primary=n_primary,
        i_ref=i_ref,
        area_window=area_window,
    )


def render_magnetostatic_pro_nonlinear(
    *,
    bh_list_literal: str,
    n_primary: int,
    i_ref: float,
    area_window: float,
    nl_max_iter: int = NL_MAX_ITER,
    nl_tol: float = NL_TOL,
    nl_relax: float = NL_RELAXATION,
) -> str:
    """
    Nonlinear Frohlich .pro: ν(B) interpolation + Picard IterativeLoop.

    Args:
        bh_list_literal: GetDP `{B0, nu0, B1, nu1, ...}` literal
            от `FrohlichBHCurve.as_getdp_list_literal()`.
        n_primary: число витков primary.
        i_ref: reference current (A).
        area_window: площадь окна (m²) для J_density.
        nl_max_iter: max iterations IterativeLoop (default 50).
        nl_tol: convergence tolerance (default 1e-5).
        nl_relax: Picard relaxation factor (default 0.7;
            требуется в deep saturation — см. T129 Analyze W1).

    """
    return PRO_TEMPLATE_NONLINEAR.format(
        bh_list_literal=bh_list_literal,
        n_primary=n_primary,
        i_ref=i_ref,
        area_window=area_window,
        nl_max_iter=nl_max_iter,
        nl_tol=nl_tol,
        nl_relax=nl_relax,
    )
