"""
GetDP magnetostatic .pro template (T113 Phase 2C).

Portирован из `scripts/pilot/getdp/magnetostatic.pro` (pilot Stage B+C,
commit 9c42042; 5 итераций debug на BF_PerpendicularEdge + Vector[Jz]
+ split current direction).

4 параметра подставляются адаптером per-component:
- `mur_iron` — relative permeability iron (`Core` region).
  Phase 2C: hardcoded 8000 (Nanoperm linear μ_initial); реальный
  per-material μ из PyOM `get_core_materials()[i]['initialPermeability']`
  — Phase 2D follow-up (с fallback на 8000 если material data
  отсутствует).
- `n_primary` — число витков primary winding.
- `i_ref` — reference current (1.0 A штатно для self-inductance).
- `area_window` — площадь окна primary (m²) для J_density расчёта.
"""

from __future__ import annotations

PRO_TEMPLATE = """\
// efactory adapters.outbound.fem_solver_getdp magnetostatic .pro
// Generated by pro_template.render() — НЕ ПРАВИТЬ ВРУЧНУЮ
//
// 2D-planar magnetostatic: vector potential A_z формулировка через
// BF_PerpendicularEdge. Lp = 2 W / I_ref² где W — energy_per_depth
// × core_depth (умножается на стороне adapter'а).
//
// PG mapping (см. geometry.emit_e_core_geo):
//   1=Core 2=Primary 3=Secondary 4=GapC 5=GapL 6=GapR 7=Air 8=Infinity

Group {{
  Core      = Region[1];
  Primary   = Region[2];
  Secondary = Region[3];
  GapC      = Region[4];
  GapL      = Region[5];
  GapR      = Region[6];
  Air       = Region[7];
  Infinity  = Region[8];

  Iron     = Region[{{Core}}];
  NonIron  = Region[{{Primary, Secondary, GapC, GapL, GapR, Air}}];
  Domain   = Region[{{Iron, NonIron}}];
}}

Function {{
  mu0      = 4*Pi*1e-7;
  mur_iron = {mur_iron};

  nu[Iron]     = 1.0 / (mu0 * mur_iron);
  nu[NonIron]  = 1.0 / mu0;

  // Coil topology (per pilot Stage B+C debug): split current direction
  // — +Jz в Primary window, -Jz в Secondary (reinterpreted как
  // return-leg). Без split одно-окно prescription = одиночный провод,
  // Lp завышена ~2.8×.
  N_primary    = {n_primary};
  I_ref        = {i_ref:g};
  area_window  = {area_window:g};
  J_density    = N_primary * I_ref / area_window;

  js[Primary]   = Vector[0, 0,  J_density];
  js[Secondary] = Vector[0, 0, -J_density];
}}

Constraint {{
  {{ Name MVP_2D;
    Case {{
      {{ Region Infinity; Value 0.; }}
    }}
  }}
}}

FunctionSpace {{
  {{ Name Hcurl_a_2D; Type Form1P;
    BasisFunction {{
      {{ Name sn; NameOfCoef an;
        Function BF_PerpendicularEdge;
        Support Domain; Entity NodesOf[All]; }}
    }}
    Constraint {{
      {{ NameOfCoef an; EntityType NodesOf; NameOfConstraint MVP_2D; }}
    }}
  }}
}}

Jacobian {{
  {{ Name Vol; Case {{ {{ Region All; Jacobian Vol; }} }} }}
}}

Integration {{
  {{ Name I1;
    Case {{
      {{ Type Gauss;
        Case {{
          {{ GeoElement Triangle;  NumberOfPoints  3; }}
          {{ GeoElement Triangle2; NumberOfPoints  6; }}
          {{ GeoElement Line;      NumberOfPoints  1; }}
          {{ GeoElement Line2;     NumberOfPoints  3; }}
        }}
      }}
    }}
  }}
}}

Formulation {{
  {{ Name Magnetostatics_2D; Type FemEquation;
    Quantity {{
      {{ Name a; Type Local; NameOfSpace Hcurl_a_2D; }}
    }}
    Equation {{
      Galerkin {{ [ nu[] * Dof{{d a}}, {{d a}} ];
                 In Domain; Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Primary;   Jacobian Vol; Integration I1; }}
      Galerkin {{ [ -js[], {{a}} ];
                 In Secondary; Jacobian Vol; Integration I1; }}
    }}
  }}
}}

Resolution {{
  {{ Name Mag2D;
    System {{
      {{ Name A; NameOfFormulation Magnetostatics_2D; }}
    }}
    Operation {{
      Generate[A]; Solve[A]; SaveSolution[A];
      PostOperation[Mag2D];
    }}
  }}
}}

PostProcessing {{
  {{ Name Mag2D; NameOfFormulation Magnetostatics_2D;
    Quantity {{
      {{ Name energy_per_depth;
        Value {{
          Integral {{ [ 0.5 * nu[] * {{d a}} * {{d a}} ];
                     In Domain; Jacobian Vol; Integration I1; }}
        }}
      }}
    }}
  }}
}}

PostOperation {{
  {{ Name Mag2D; NameOfPostProcessing Mag2D;
    Operation {{
      Print[ energy_per_depth[Domain], OnGlobal, Format Table,
             File "energy_per_depth.txt" ];
    }}
  }}
}}
"""


def render_magnetostatic_pro(
    *,
    mur_iron: float,
    n_primary: int,
    i_ref: float,
    area_window: float,
) -> str:
    """Подставить параметры в GetDP magnetostatic .pro template."""
    return PRO_TEMPLATE.format(
        mur_iron=mur_iron,
        n_primary=n_primary,
        i_ref=i_ref,
        area_window=area_window,
    )
