"""
Elmer `.sif` template renderer (T133 Phase 1 linear + Phase 2 nonlinear).

Эмитит `.sif` для Elmer `MagnetoDynamics2D` solver на T113-shaped mesh
(7 bodies из `emit_e_core_geo`: core/primary/secondary/3 gaps/air;
1 boundary "infinity"). Phase 1 — linear `μ_r` Iron. Phase 2 —
nonlinear Frohlich через `H-B Curve = Variable Coupled iter / Real
cubic / ... End` (синтаксис verified в T133 Phase 0 probe;
см. auto-memory `feedback_elmer_2d_keyword_pitfalls`).

Топология T133 — **single-coil**: только Primary (Body 2) несёт ток
(+Jz), Secondary (Body 3) трактуется как air (Material 1). Это контрастирует
с T113 split-coil (`±Jz` antisymmetric). Outer boundary использует
`Infinity BC = Logical True` (Robin natural BC, T133 Phase 0 verified),
не Dirichlet `A = 0` (T113 convention).

Body / Boundary numbering зависит от `ElmerGrid 14 2 ... -autoclean`,
который renumber'ит Physical tags в 1-indexed sequential по порядку
emit_e_core_geo: core=1, primary=2, secondary=3, gap_center=4,
gap_left=5, gap_right=6, air=7; infinity boundary=1.

`PrimaryRegion = Logical True` на Body 2 — body-property mask для
SaveScalars `Mask Name = "PrimaryRegion"`, по которой считается
`body int(A)` (Lp через energy method: `Lp = 2·J·depth·∫_Primary A dS / I²`).
"""

from __future__ import annotations


def render_magnetostatic_sif_linear(
    *,
    mur_iron: float,
    n_primary: int,
    i_ref: float,
    area_window: float,
) -> str:
    """
    Render Elmer linear magnetostatic `.sif` (T133 Phase 1).

    Args:
        mur_iron: relative permeability of iron core (Material 2).
        n_primary: число витков первичной обмотки.
        i_ref: reference current [A] для self-inductance расчёта.
        area_window: площадь окна обмотки [m²] (для J = N·I/A).

    Returns:
        .sif text ready для `ElmerSolver <file>.sif` после mesh-elmer/
        materialization (через `ElmerGrid 14 2 mesh.msh -autoclean -out
        mesh-elmer`).

    """
    j_density = n_primary * i_ref / area_window
    return _SIF_LINEAR_TEMPLATE.format(
        mur_iron=mur_iron,
        j_density=j_density,
    )


def render_magnetostatic_sif_nonlinear(
    *,
    h_b_pairs: tuple[tuple[float, float], ...],
    n_primary: int,
    i_value: float,
    area_window: float,
) -> str:
    """
    Render Elmer nonlinear magnetostatic `.sif` (T133 Phase 2).

    Использует Iron H-B Curve через `Variable Coupled iter / Real cubic`
    (auto-memory `feedback_elmer_2d_keyword_pitfalls` — точный syntax
    verified Phase 0 probe). Newton-Raphson после 3 Picard iterations,
    relaxation factor 0.7 (Frohlich saturation knee может требовать
    damping).

    Args:
        h_b_pairs: ((H_1, B_1), (H_2, B_2), ...) — от
            `FrohlichBHCurve.h_b_pairs()`. Monotonic по B, начинается
            с (0, 0).
        n_primary: число витков первичной обмотки.
        i_value: фактический ток обмотки [A] для этого probe-solve
            (для central-diff: I_dc ± ΔI/2).
        area_window: площадь окна обмотки [m²] (для J = N·I/A).

    Returns:
        .sif text ready для `ElmerSolver <file>.sif` после mesh-elmer/
        materialization.

    """
    j_density = n_primary * i_value / area_window
    hb_table_lines = '\n'.join(f'      {h:.9g}  {b:.9g}' for h, b in h_b_pairs)
    return _SIF_NONLINEAR_TEMPLATE.format(
        hb_table=hb_table_lines,
        j_density=j_density,
    )


# Body numbering после ElmerGrid -autoclean:
#   1 = core, 2 = primary, 3 = secondary, 4 = gap_center,
#   5 = gap_left, 6 = gap_right, 7 = air.
# Boundary: 1 = infinity (outer).
_SIF_LINEAR_TEMPLATE = """\
! T133 Phase 1 — Elmer 2D-planar magnetostatic, linear iron + single-coil
! + Infinity BC. Generated by efactory
! adapters.outbound.fem_solver_elmer.sif_template.render_magnetostatic_sif_linear

Header
  Mesh DB "." "mesh-elmer"
End

Simulation
  Coordinate System = "Cartesian 2D"
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = "Steady state"
  Steady State Max Iterations = 1
  Output Intervals = 1
End

Constants
  Permeability of Vacuum = Real 1.25663706143592e-6
End

! ===== Bodies =====
Body 1
  Name = "Core"
  Target Bodies(1) = 1
  Equation = 1
  Material = 2
End

Body 2
  Name = "Primary"
  Target Bodies(1) = 2
  Equation = 1
  Material = 1
  Body Force = 1
  PrimaryRegion = Logical True
End

Body 3
  Name = "Secondary"
  Target Bodies(1) = 3
  Equation = 1
  Material = 1
End

Body 4
  Name = "GapCenter"
  Target Bodies(1) = 4
  Equation = 1
  Material = 1
End

Body 5
  Name = "GapLeft"
  Target Bodies(1) = 5
  Equation = 1
  Material = 1
End

Body 6
  Name = "GapRight"
  Target Bodies(1) = 6
  Equation = 1
  Material = 1
End

Body 7
  Name = "Air"
  Target Bodies(1) = 7
  Equation = 1
  Material = 1
End

! ===== Materials =====
Material 1
  Name = "Air"
  Relative Permeability = Real 1.0
  Electric Conductivity = Real 0.0
End

Material 2
  Name = "Iron_Linear"
  Relative Permeability = Real {mur_iron:.9g}
  Electric Conductivity = Real 0.0
End

! ===== Body Force =====
Body Force 1
  Name = "PrimaryCurrent_plus_Jz"
  Current Density = Real {j_density:.9g}
End

! ===== Equation =====
Equation 1
  Name = "MagnetoDynamics2D"
  Active Solvers(2) = 1 2
End

! ===== Solver 1: A-V magnetic vector potential =====
Solver 1
  Equation = "MgDyn2D"
  Variable = "A"
  Variable DOFs = 1
  Procedure = "MagnetoDynamics2D" "MagnetoDynamics2D"

  Linear System Solver = "Iterative"
  Linear System Iterative Method = "BiCGStabL"
  Linear System Max Iterations = 5000
  Linear System Convergence Tolerance = 1.0e-10
  Linear System Preconditioning = "ILU0"
  Linear System Residual Output = 100

  Nonlinear System Max Iterations = 1
End

! ===== Solver 2: SaveScalars — body int A над Primary region =====
! (feedback_elmer_savescalars_quirks: solver MUST be в Active Solvers выше,
! "body int" + Mask Name, не "body integral".)
Solver 2
  Equation = "SaveScalars"
  Procedure = "SaveData" "SaveScalars"
  Filename = "scalars.dat"

  Variable 1 = "A"
  Operator 1 = "body int"
  Mask Name 1 = "PrimaryRegion"
End

! ===== Boundary Condition =====
! Outer boundary — Infinity BC = Robin-type natural (T133 Phase 0 verified
! в probe_infinity_bc.sif). После ElmerGrid -autoclean Physical Curve
! "infinity" maps в Boundary 1.
Boundary Condition 1
  Name = "Infinity"
  Target Boundaries(1) = 1
  Infinity BC = Logical True
End
"""


# Nonlinear (Frohlich H-B Curve) template — отличия от linear:
#   1. Material 2 (Iron): "H-B Curve = Variable Coupled iter / Real cubic /
#      table / End" вместо "Relative Permeability".
#   2. Solver 1: Nonlinear System Max Iterations = 50, Convergence
#      Tolerance 1e-5, Newton After Iterations 3, Relaxation Factor 0.7
#      (W3 mitigation для Frohlich knee).
# Body / BC / Body Force структура та же — single-coil Primary +Jz,
# Infinity BC на outer.
_SIF_NONLINEAR_TEMPLATE = """\
! T133 Phase 2 — Elmer 2D-planar magnetostatic, nonlinear Frohlich +
! single-coil + Infinity BC. Generated by efactory
! adapters.outbound.fem_solver_elmer.sif_template.render_magnetostatic_sif_nonlinear

Header
  Mesh DB "." "mesh-elmer"
End

Simulation
  Coordinate System = "Cartesian 2D"
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = "Steady state"
  Steady State Max Iterations = 1
  Output Intervals = 1
End

Constants
  Permeability of Vacuum = Real 1.25663706143592e-6
End

! ===== Bodies =====
Body 1
  Name = "Core"
  Target Bodies(1) = 1
  Equation = 1
  Material = 2
End

Body 2
  Name = "Primary"
  Target Bodies(1) = 2
  Equation = 1
  Material = 1
  Body Force = 1
  PrimaryRegion = Logical True
End

Body 3
  Name = "Secondary"
  Target Bodies(1) = 3
  Equation = 1
  Material = 1
End

Body 4
  Name = "GapCenter"
  Target Bodies(1) = 4
  Equation = 1
  Material = 1
End

Body 5
  Name = "GapLeft"
  Target Bodies(1) = 5
  Equation = 1
  Material = 1
End

Body 6
  Name = "GapRight"
  Target Bodies(1) = 6
  Equation = 1
  Material = 1
End

Body 7
  Name = "Air"
  Target Bodies(1) = 7
  Equation = 1
  Material = 1
End

! ===== Materials =====
Material 1
  Name = "Air"
  Relative Permeability = Real 1.0
  Electric Conductivity = Real 0.0
End

Material 2
  Name = "Iron_Frohlich"
  Electric Conductivity = Real 0.0
  ! H-B Curve via FrohlichBHCurve.h_b_pairs() (auto-memory
  ! feedback_elmer_2d_keyword_pitfalls: "Variable Coupled iter" +
  ! "Real cubic"; Cubic spline между точками per binary strings).
  H-B Curve = Variable Coupled iter
    Real cubic
{hb_table}
    End
End

! ===== Body Force =====
Body Force 1
  Name = "PrimaryCurrent_plus_Jz"
  Current Density = Real {j_density:.9g}
End

! ===== Equation =====
Equation 1
  Name = "MagnetoDynamics2D"
  Active Solvers(2) = 1 2
End

! ===== Solver 1: A-V с Newton-Raphson iteration =====
Solver 1
  Equation = "MgDyn2D"
  Variable = "A"
  Variable DOFs = 1
  Procedure = "MagnetoDynamics2D" "MagnetoDynamics2D"

  Linear System Solver = "Iterative"
  Linear System Iterative Method = "BiCGStabL"
  Linear System Max Iterations = 5000
  Linear System Convergence Tolerance = 1.0e-10
  Linear System Preconditioning = "ILU0"
  Linear System Residual Output = 100

  Nonlinear System Max Iterations = 50
  Nonlinear System Convergence Tolerance = 1.0e-5
  Nonlinear System Newton After Iterations = 3
  Nonlinear System Newton After Tolerance = 1.0e-3
  Nonlinear System Relaxation Factor = 0.7
End

! ===== Solver 2: SaveScalars body int A на Primary =====
Solver 2
  Equation = "SaveScalars"
  Procedure = "SaveData" "SaveScalars"
  Filename = "scalars.dat"

  Variable 1 = "A"
  Operator 1 = "body int"
  Mask Name 1 = "PrimaryRegion"
End

! ===== Boundary Condition =====
Boundary Condition 1
  Name = "Infinity"
  Target Boundaries(1) = 1
  Infinity BC = Logical True
End
"""
